from __future__ import annotations

import re
from io import BytesIO
from datetime import datetime, timezone
from typing import Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from xml.sax.saxutils import escape


METRIC_EXPLANATIONS = {
    "Sales": "Revenue earned from the company's core operations before expenses.",
    "Expenses": "Operating costs consumed in generating revenue; compare their growth with sales.",
    "Operating Profit": "Profit from core operations before interest, tax, and non-operating items.",
    "OPM %": "Operating profit as a percentage of sales, showing core pricing power and cost control.",
    "Other Income": "Income outside core operations; heavy dependence can reduce earnings quality.",
    "Interest": "Financing cost on borrowings and other obligations.",
    "Depreciation": "Non-cash charge allocating the cost of long-lived assets over their useful lives.",
    "Profit before tax": "Earnings after operating and financing costs but before tax.",
    "Tax %": "Effective tax burden on reported pre-tax profit.",
    "Net Profit": "Profit attributable after all reported expenses, interest, and taxes.",
    "EPS in Rs": "Net profit attributable to each share; dilution and buybacks can affect the trend.",
    "Dividend Payout %": "Share of earnings distributed as dividends rather than retained for growth.",
    "Equity Capital": "Paid-up share capital; increases can indicate issuance or dilution.",
    "Reserves": "Accumulated retained earnings and other reserves supporting net worth.",
    "Borrowings": "Interest-bearing debt; assess its movement with cash generation and interest cover.",
    "Other Liabilities": "Non-debt obligations that still represent claims on company resources.",
    "Total Liabilities": "Combined funding claims, including shareholder funds and external obligations as presented by Screener.",
    "Fixed Assets": "Long-lived operating assets used to generate revenue.",
    "CWIP": "Capital work in progress not yet ready for productive use.",
    "Investments": "Capital held in financial or strategic investments rather than core operating assets.",
    "Other Assets": "Remaining operating and financial assets not shown separately.",
    "Total Assets": "Total resources controlled by the company and funded by capital and liabilities.",
    "Cash from Operating Activity": "Cash generated by core operations after working-capital movements.",
    "Cash from Investing Activity": "Cash spent on or received from assets and investments.",
    "Cash from Financing Activity": "Cash flows involving debt, equity, dividends, and other financing.",
    "Net Cash Flow": "Net change in cash after operating, investing, and financing activities.",
    "Free Cash Flow": "Operating cash remaining after capital expenditure, available for debt reduction or distribution.",
    "CFO/OP": "Operating cash flow relative to operating profit, used as an earnings-quality check.",
    "Debtor Days": "Approximate collection time for receivables; a sustained rise can signal working-capital pressure.",
    "Working Capital Days": "Net operating working capital expressed in days of sales.",
    "Cash Conversion Cycle": "Time cash remains tied up in the operating cycle; lower is generally more efficient.",
    "ROCE %": "Operating return generated on capital employed in the business.",
}


def _movement(latest: Optional[float], prior: Optional[float], percentage_points: bool = False) -> Dict[str, object]:
    if latest is None or prior is None:
        return {"display": "N/M", "direction": "Insufficient history for a period comparison."}
    if percentage_points:
        change = latest - prior
        return {
            "display": f"{change:+.1f} pp",
            "direction": f"Moved {abs(change):.1f} percentage points {'higher' if change > 0 else 'lower' if change < 0 else 'and was unchanged'} from the prior annual period.",
        }
    if prior == 0:
        return {"display": "N/M", "direction": "The prior value was zero, so a percentage change is not meaningful."}
    if latest < 0 or prior < 0:
        return {"display": "N/M", "direction": "At least one period is negative, so a conventional percentage growth rate would be misleading."}
    change = (latest - prior) / abs(prior) * 100
    if abs(change) < 0.05:
        direction = "Broadly unchanged from the prior annual period."
    else:
        direction = f"{'Increased' if change > 0 else 'Decreased'} {abs(change):.1f}% from the prior annual period."
    return {"display": f"{change:+.1f}%", "direction": direction}


def _statement_rows(statement: Dict[str, object]) -> List[Dict[str, object]]:
    periods = statement.get("periods", [])
    if not isinstance(periods, list) or not isinstance(statement.get("rows"), dict):
        return []
    annual_indices = [index for index, period in enumerate(periods) if re.search(r"\b\d{4}\b", str(period))]
    latest_index = annual_indices[-1] if annual_indices else None
    prior_index = annual_indices[-2] if len(annual_indices) > 1 else None
    rows = []
    for label, points in statement.get("rows", {}).items():
        if not isinstance(points, list):
            continue
        latest = points[latest_index] if latest_index is not None and latest_index < len(points) and isinstance(points[latest_index], dict) else {}
        prior = points[prior_index] if prior_index is not None and prior_index < len(points) and isinstance(points[prior_index], dict) else {}
        percentage_points = latest.get("unit") == "%" or str(label).endswith("%")
        movement = _movement(latest.get("value"), prior.get("value"), percentage_points)
        rows.append({
            "label": label,
            "latest_period": periods[latest_index] if latest_index is not None else "Not available",
            "latest": latest.get("displayed", "Not available"),
            "prior_period": periods[prior_index] if prior_index is not None else "Not available",
            "prior": prior.get("displayed", "Not available"),
            "change_display": movement["display"],
            "interpretation": f"{METRIC_EXPLANATIONS.get(label, 'A reported line item that should be assessed in context with related statement values.')} {movement['direction']}",
        })
    return rows


def build_analyst_report(data: Dict[str, object], analysis: Dict[str, object], ticker: str = "") -> Dict[str, object]:
    statement_notes = {
        "Profit & Loss": "Evaluates operating momentum, margins, financing costs, and the quality of reported earnings.",
        "Balance Sheet": "Examines how assets are funded, whether leverage is controlled, and where capital is deployed.",
        "Cash Flows": "Tests whether accounting profit converts into cash and how that cash is invested or distributed.",
        "Ratios": "Summarizes operating efficiency and return measures derived from the financial statements.",
    }
    statements = [
        {
            "name": name,
            "note": statement_notes.get(name, "Detailed review of reported financial values."),
            "rows": _statement_rows(statement),
        }
        for name, statement in data.get("statements", {}).items()
        if isinstance(statement, dict)
    ]
    return {
        "company": data.get("company", "Company"),
        "ticker": ticker or data.get("ticker", ""),
        "source_url": data.get("source_url", ""),
        "fetched_at": data.get("fetched_at", ""),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "analysis": analysis,
        "insights": analysis["business_insights"],
        "statements": statements,
    }


def _pdf_text(value: object) -> str:
    return escape(str(value or "Not available").replace("₹", "Rs. "))


def render_analyst_pdf(report: Dict[str, object]) -> bytes:
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=17 * mm,
        bottomMargin=17 * mm,
        title=f"{report['company']} Analyst Report",
        author="InvestorLens",
    )
    sample = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle("ReportTitle", parent=sample["Title"], fontName="Helvetica-Bold", fontSize=25, leading=29, textColor=colors.HexColor("#17211c"), spaceAfter=6),
        "subtitle": ParagraphStyle("ReportSubtitle", parent=sample["BodyText"], fontName="Helvetica", fontSize=10, leading=15, textColor=colors.HexColor("#56635c"), spaceAfter=14),
        "section": ParagraphStyle("ReportSection", parent=sample["Heading2"], fontName="Helvetica-Bold", fontSize=16, leading=20, textColor=colors.HexColor("#17211c"), spaceBefore=12, spaceAfter=8),
        "heading": ParagraphStyle("ReportHeading", parent=sample["Heading3"], fontName="Helvetica-Bold", fontSize=11, leading=14, textColor=colors.HexColor("#147d59"), spaceBefore=8, spaceAfter=4),
        "body": ParagraphStyle("ReportBody", parent=sample["BodyText"], fontName="Helvetica", fontSize=8.5, leading=12, textColor=colors.HexColor("#26332c"), spaceAfter=6),
        "small": ParagraphStyle("ReportSmall", parent=sample["BodyText"], fontName="Helvetica", fontSize=7, leading=9, textColor=colors.HexColor("#56635c")),
        "cell": ParagraphStyle("ReportCell", parent=sample["BodyText"], fontName="Helvetica", fontSize=6.5, leading=8, textColor=colors.HexColor("#26332c")),
        "cell_bold": ParagraphStyle("ReportCellBold", parent=sample["BodyText"], fontName="Helvetica-Bold", fontSize=6.5, leading=8, textColor=colors.HexColor("#17211c")),
        "score": ParagraphStyle("ReportScore", parent=sample["Title"], fontName="Helvetica-Bold", fontSize=20, leading=23, alignment=TA_CENTER, textColor=colors.white),
    }
    story = []
    insights = report["insights"]
    analysis = report["analysis"]

    story.extend([
        Paragraph("INVESTORLENS ANALYST REPORT", styles["heading"]),
        Paragraph(_pdf_text(report["company"]), styles["title"]),
        Paragraph("In-depth, accounting-led review of performance, financial position, cash generation, valuation, peer context, and decision risks.", styles["subtitle"]),
    ])
    meta = Table([
        ["Ticker", _pdf_text(report["ticker"]), "Data fetched", _pdf_text(report["fetched_at"])],
        ["Source", Paragraph(f'<link href="{_pdf_text(report["source_url"])}">Screener company page</link>', styles["small"]), "Generated", _pdf_text(report["generated_at"])],
    ], colWidths=[18 * mm, 38 * mm, 24 * mm, 95 * mm])
    meta.setStyle(TableStyle([("FONTNAME", (0, 0), (-1, -1), "Helvetica"), ("FONTSIZE", (0, 0), (-1, -1), 7), ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#56635c")), ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#edf0ea")), ("GRID", (0, 0), (-1, -1), .3, colors.HexColor("#d9dfd7")), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("PADDING", (0, 0), (-1, -1), 6)]))
    story.extend([meta, Spacer(1, 6 * mm)])

    verdict = Table([
        [Paragraph(f"{analysis['score']}<br/><font size='7'>/ 100</font>", styles["score"]), Paragraph(f"<b>{_pdf_text(insights['stance'])}</b><br/>{_pdf_text(insights['action'])}<br/><br/><b>Monitoring horizon:</b> {_pdf_text(insights['wait_window'])}<br/><b>Model confidence:</b> {_pdf_text(insights['confidence'])}", styles["body"])],
    ], colWidths=[28 * mm, 147 * mm])
    verdict.setStyle(TableStyle([("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#147d59")), ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#edf3ef")), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("PADDING", (0, 0), (-1, -1), 10)]))
    story.extend([verdict, Paragraph("Executive assessment", styles["section"])])
    for item in insights["executive_summary"]:
        story.append(Paragraph(f"• {_pdf_text(item)}", styles["body"]))

    module_rows = [[Paragraph("Assessment module", styles["cell_bold"]), Paragraph("Score", styles["cell_bold"])]]
    module_rows.extend([[Paragraph(_pdf_text(module["name"]), styles["cell"]), f"{module['score']} / {module['max']}"] for module in analysis["modules"]])
    modules = Table(module_rows, colWidths=[145 * mm, 30 * mm], repeatRows=1)
    modules.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#24485b")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("GRID", (0, 0), (-1, -1), .3, colors.HexColor("#d9dfd7")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 5)]))
    story.extend([modules, Paragraph("Business quality under the lens", styles["section"])])
    for dimension in insights["dimensions"]:
        story.append(Paragraph(f"{_pdf_text(dimension['title'])} · {_pdf_text(dimension['rating'])}", styles["heading"]))
        story.append(Paragraph(_pdf_text(dimension["analysis"]), styles["body"]))
        if dimension.get("detail"):
            story.append(Paragraph(_pdf_text(dimension["detail"]), styles["body"]))

    comparison = insights["industry_comparison"]
    story.extend([PageBreak(), Paragraph("Direct peer comparison", styles["section"]), Paragraph(f"<b>Industry:</b> {_pdf_text(comparison['industry'])}<br/><b>Accounting period:</b> {_pdf_text(comparison['accounting_period'])}<br/><b>Peers included:</b> {comparison['sample_size']} · <b>Excluded without matching data:</b> {comparison['excluded_count']}<br/>{_pdf_text(comparison['methodology'])} {_pdf_text(comparison['price_basis'])}", styles["body"])])
    peer_rows = [[Paragraph(text, styles["cell_bold"]) for text in ("Metric", "Company (annual period)", "Peer median (same period)", "Difference", "Assessment")]]
    peer_rows.extend([[Paragraph(_pdf_text(item["label"]), styles["cell"]), f"{item['company']}{item['unit']}", f"{item['peer_median']}{item['unit']}", f"{item['difference_percent']:+.1f}%", item["assessment"]] for item in comparison["comparisons"]])
    peer_table = Table(peer_rows, colWidths=[55 * mm, 28 * mm, 32 * mm, 28 * mm, 32 * mm], repeatRows=1)
    peer_table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#24485b")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("GRID", (0, 0), (-1, -1), .3, colors.HexColor("#d9dfd7")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 5)]))
    story.append(peer_table)

    for title, items in (("Supporting evidence", insights["why_choose"]), ("Reasons for caution", insights["why_not"]), ("Confirmation triggers", insights["confirmations"]), ("Thesis-break warnings", insights["invalidations"]), ("Further due diligence", insights["research_gaps"])):
        story.append(Paragraph(title, styles["section"]))
        for item in items:
            story.append(Paragraph(f"• {_pdf_text(item)}", styles["body"]))

    story.extend([PageBreak(), Paragraph("Financial statement review", styles["section"]), Paragraph("Every available annual line item is shown with its latest and prior reported value. Movement is descriptive and must be interpreted with related statement values.", styles["body"])])
    for statement in report["statements"]:
        story.extend([Paragraph(_pdf_text(statement["name"]), styles["section"]), Paragraph(_pdf_text(statement["note"]), styles["body"])])
        rows = [[Paragraph(text, styles["cell_bold"]) for text in ("Line item", "Latest", "Prior", "Change", "Analyst interpretation")]]
        rows.extend([
            [
                Paragraph(_pdf_text(row["label"]), styles["cell_bold"]),
                Paragraph(f"{_pdf_text(row['latest'])}<br/><font color='#68736d'>{_pdf_text(row['latest_period'])}</font>", styles["cell"]),
                Paragraph(f"{_pdf_text(row['prior'])}<br/><font color='#68736d'>{_pdf_text(row['prior_period'])}</font>", styles["cell"]),
                Paragraph(_pdf_text(row["change_display"]), styles["cell"]),
                Paragraph(_pdf_text(row["interpretation"]), styles["cell"]),
            ]
            for row in statement["rows"]
        ])
        table = Table(rows, colWidths=[31 * mm, 23 * mm, 23 * mm, 19 * mm, 79 * mm], repeatRows=1)
        table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#24485b")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("GRID", (0, 0), (-1, -1), .25, colors.HexColor("#d9dfd7")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 4), ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f7f3")])]))
        story.append(table)

    story.extend([Spacer(1, 5 * mm), Paragraph(_pdf_text(insights["disclaimer"]), styles["small"])])

    def page_footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#68736d"))
        canvas.drawString(15 * mm, 9 * mm, "InvestorLens · Screener-sourced financial research")
        canvas.drawRightString(A4[0] - 15 * mm, 9 * mm, f"Page {doc.page}")
        canvas.restoreState()

    document.build(story, onFirstPage=page_footer, onLaterPages=page_footer)
    return buffer.getvalue()